import Vue from 'vue'
import { Button, NavBar, Form, Field, CountDown, Tabbar, TabbarItem, Image, GridItem, Grid, Cell, Icon, Tab, Tabs, List, PullRefresh, Popup, Search, Empty, Sticky, Loading, Divider } from 'vant'
Vue.use(Button)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(CountDown)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Image)
Vue.use(GridItem)
Vue.use(Grid)
Vue.use(Cell)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Popup)
Vue.use(Search)
Vue.use(Empty)
Vue.use(Sticky)
Vue.use(Loading)
Vue.use(Divider)
